### ISSUE TITLE
Swagger 2/OpenApi 3.0 support for Rest API

### ISSUE THREAD

**Issue by pesoklp13** [Kamahl19/react-starter#34]
if you would like to use Swagger for express server. I can provide integration with this repo https://github.com/pesoklp13/swagger-express-ts2/tree/2.0.0_paths_object also in rewrite (refactoring) state, but will be soon prepared to implement support for openapi 3.0

**Comment by Kamahl19** [comment]
I plan to release the express-starter in separate repo, until now it was part of this repo but it has been removed in the `rewrite` branch. It would definitely be great to have swagger and also typescript there, but react-starter is priority right now since we have no new project in scope that would need node backend right now

**Comment by Kamahl19** [comment]
i will create an express-starter repo soon so that we can copy this issue there

**Comment by Kamahl19** [comment]
Closing this issue since this repo is not containing the Nodejs backend anymore, it's in a separate repo now.
